apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nodejs-sample-build
  labels:
    app: nodejs-sample
spec:
  source:
    type: Git
    git:
      uri: https://github.com/sclorg/nodejs-ex.git
      ref: master
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: nodejs:16-ubi8
      env:
      - name: NODE_ENV
        value: production
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-sample:latest
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: nodejs:16-ubi8
