apiVersion: apps/v1
kind: Deployment
metadata:
  name: cakephp-app
spec:
  template:
    spec:
      containers:
      - name: cakephp-app
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
