apiVersion: apps/v1
kind: Deployment
metadata:
  name: cakephp-app
spec:
  template:
    spec:
      containers:
      - name: cakephp-app
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
